name: bizbultest
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  screenshot: ^1.2.3
  flutter_tts: ^3.2.3
  image_gallery_saver: ^1.6.9
  firebase_dynamic_links: ^5.0.15
  panorama: ^0.4.1
  webview_flutter: ^2.0.12
  font_awesome_flutter: ^10.3.0
  country_codes: ^2.0.1
  chewie: any

  just_audio: ^0.9.28
  # firebase_core_platform_interface: 4.5.1
  # firebase_messaging: ^13.0.4
  firebase_messaging: ^14.2.5
  fluttertoast: ^8.1.2
  html: ^0.15.1
  carousel_slider: ^4.0.0
  flutter_parsed_text: ^2.2.1
  pull_to_refresh: ^2.0.0
  exif: ^3.0.0
  flutter_spinkit: ^5.1.0
  gesture_x_detector: ^1.0.0
  flutter_translate: ^4.0.3
  cached_network_image: ^3.2.3
  http: ^0.13.0
  pin_code_fields: ^7.3.0
  matrix_gesture_detector: ^0.1.0
  shared_preferences: ^2.1.0
  #  ^2.0.18
  # ^2.0.6
  translator: ^0.1.7
  share: ^2.0.4
  sizer: ^2.0.13
  persistent_bottom_nav_bar: ^4.0.2
  #  ^5.0.2
  flutter_map:
  transparent_image:
  native_device_orientation: ^1.1.4
  visibility_detector: ^0.3.2
  detectable_text_field: ^2.0.3
  latlng: ^0.2.0
  image_picker: ^0.8.3+2
  # zefyr: ^0.12.0
  quill_delta:
  file_picker: ^4.0.0
  charts_flutter:
    git:
      url: https://github.com/google/charts.git
      path: charts_flutter
  rich_text_view: ^0.0.3
  # ^1.2.0
  google_fonts: ^4.0.1
  flutter_share: ^2.0.0
  csv: ^5.0.0
  hexcolor: ^3.0.1
  # native_pdf_view: ^4.1.0
  # cached_video_player: ^2.0.0-dev.1
  modal_bottom_sheet: ^2.0.0
  storage_path: ^0.2.0
  path: ^1.8.0
  path_provider: ^2.0.2
  # simple_image_crop: ^1.0.0
  camerawesome: ^0.3.0
  shared_preferences_android:

  # ^1.2.1
  preload_page_view: ^0.1.6
  permission_handler: ^10.2.0
  flutter_staggered_grid_view: ^0.4.1
  #  ^0.6.2
  # git: git://github.com/clragon/flutter_staggered_grid_view.git
  video_player:
  video_editor: ^2.4.0
  flick_video_player: ^0.5.0
  skeleton_text: ^3.0.0
  photo_manager: ^2.5.2
  multipart_request: ^0.3.1
  optimized_cached_image: ^3.0.0
  device_info: ^2.0.2
  image_downloader: ^0.31.0
  percent_indicator: ^3.0.1
  image_crop: any
  camera: ^0.10.0+3
  url_launcher: ^6.0.4
  photofilters: ^3.0.1
  flutter_exif_rotation: ^0.5.1
  image_editor: ^1.0.0
  extended_image: ^6.1.0
  helpers: ^1.1.4
  sliding_up_panel: ^2.0.0+1
  material_segmented_control: ^4.2.0
  readmore: ^2.1.0
  syncfusion_flutter_charts: any
  logger: ^1.1.0
  jiffy: ^5.0.0
  polls: ^1.0.1
  # enough_giphy_flutter: any

  # photo_view: ^0.11.1
  gallery_saver: ^2.1.3
  pausable_timer: ^1.0.0+1
  flutter_keyboard_visibility: any
  # flutter_keyboard_visibility: ^5.0.3
  vibration: any
  # vibration: ^1.7.4
  contacts_service:

  # android_intent:
  emoji_picker:
  open_file: ^3.2.1
  native_pdf_renderer: any
  # ^5.0.0+1
  dio: ^5.0.1
  audioplayers: 0.20.0
  # ^3.0.1
  #  flutter_custom_tabs: ^1.0.3
  record: ^4.4.4
  wechat_assets_picker: ^8.3.2
  video_thumbnail: ^0.5.3
  syncfusion_flutter_maps: ^20.3.61
  location: ^4.3.0
  maps_launcher:
  zefyrka: ^1.2.0-dev.1
  scrollable_positioned_list: ^0.3.1
  scroll_to_index: ^3.0.1
  flutter_native_image: ^0.0.6+1
  video_compress: ^3.1.0
  swipe_to: ^1.0.2
  connectivity: ^3.0.6
  get: ^4.3.6
  giphy_picker: ^3.0.1
  giphy_get: any
  flash: ^2.0.3
  media_scanner: ^2.0.0
  slider_button: ^2.0.0
  flutter_inappwebview: ^5.3.2

  wakelock: ^0.6.2
  rxdart: ^0.27.2
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.1.6
  webviewx: ^0.2.1
  http_auth: ^1.0.1
  avatar_glow: ^2.0.2
  speech_to_text: ^6.1.1
  flutter_material_color_picker: ^1.1.0+2
  # flutter_ffmpeg: any

  firebase_core:
  # firebase_analytics: 8.3.0
  # agora_rtc_engine: ^4.0.6
  agora_rtc_engine:
    any
    # flutter_local_notifications: ^8.1.1+1
  # flutter_local_notifications: any
  flutter_paypal: any
  # agora_rtm: ^1.0.1

  overlay_support: ^2.1.0
  # awesome_notifications: ^0.0.6+10
  flutter_ringtone_player: ^3.0.0
  firebase_auth: ^4.2.9
  linkfy_text: ^1.1.5
  agora_uikit: any
  callkeep: ^0.3.1
  fl_chart: ^0.36.3
  #  ^0.61.0
  high_chart: ^2.0.1
  provider: ^6.0.5
  dart_ipify: ^1.1.1
  flutter_rating_bar: ^4.0.0
  commons:
  flutter_phoenix: ^1.0.0
  is_lock_screen: ^2.0.0
  modal_progress_hud: ^0.1.3
  package_info: ^2.0.2
  intl: ^0.17.0
  uuid: ^3.0.5
  checkbox_grouped: ^1.8.0
  country_picker: ^2.0.8
  flutter_html:
  flutter_typeahead: ^4.3.1
  google_maps_flutter: any
  geocoding: ^2.0.1
  socket_io_client: ^2.0.0
  sqflite: ^2.0.0+4
  grouped_list: ^5.1.2
  awesome_notifications: ^0.7.3
  flutter_image_compress: ^1.1.0
  flutter_local_notifications: ^12.0.4
  geolocator: ^9.0.2
  geolocator_web: ^2.1.5
  playify: ^2.2.0
  page_transition: "^2.0.9"
  confetti: any
  # stripe_payment: ^1.0.6
  # flutter_credit_card: 3.0.4
  # card_scanner: 0.2.2

  # music_kit:

#   flutter_staggered_grid_view:
#     git: git://github.com/clragon/flutter_staggered_grid_view.git
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/tune/diallerTone.mp3
    - jsonFile/languagetext.json
    - assets/Bright_Wallpapers/
    - assets/Dark_Wallpapers/
    - assets/Solid_Wallpapers/
    - assets/send.png
    - assets/card.png
    - assets/dot_menu.png
    - assets/user_placeholder.png
    - assets/user_dummy.jpg
    - assets/delete.png
    - assets/scanner.png
    - assets/back_arrow.png
    - assets/down_arrow.png
    - assets/card.png
    - assets/right_tick.png
    - assets/check.png
    - assets/uncheck.png
    - assets/clock.png
    - assets/right_arrow.png
    - assets/smartphone.png
    - assets/pay_contact.png
    - assets/withdrow.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: TradeIicon
      fonts:
        - asset: assets/fonts/TradeIicon.ttf
    - family: WalletIcon
      fonts:
        - asset: assets/fonts/WalletIcon.ttf
    - family: AllCatIcon
      fonts:
        - asset: assets/fonts/AllCatIcon.ttf
    - family: Tradesmanlogo
      fonts:
        - asset: assets/fonts/TradesmanLogo.ttf
    - family: BuzzfeedLogo
      fonts:
        - asset: assets/fonts/BuzzfeedLogo.ttf
    - family: ShopbuzLogo
      fonts:
        - asset: assets/fonts/ShopbuzLogo.ttf
    - family: BuzzerfeedIcons
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
    - family: Georgie
      fonts:
        - asset: assets/fonts/georgia.ttf
    - family: Arial
      fonts:
        - asset: assets/fonts/arial.ttf
    - family: Segio
      fonts:
        - asset: assets/fonts/Segoe.ttf
    - family: DomaineDisplay
      fonts:
        - asset: assets/fonts/DomaineDispNar-Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
