/// Flutter icons BuzzfeedLogo
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  BuzzfeedLogo
///      fonts:
///       - asset: fonts/BuzzfeedLogo.ttf
///
///
///
import 'package:flutter/widgets.dart';

class BuzzfeedLogo {
  BuzzfeedLogo._();

  static const _kFontFam = 'BuzzfeedLogo';
  static const String? _kFontPkg = null;

  static const IconData buzzfeedlogo =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
