/// Flutter icons AllCat
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllCat
///      fonts:
///       - asset: fonts/AllCat.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AllCat {
  AllCat._();

  static const _kFontFam = 'AllCat';
  static const String? _kFontPkg = null;

  static const IconData menu_icon__1_ =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
