/// Flutter icons AllCatIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllCatIcon
///      fonts:
///       - asset: fonts/AllCatIcon.ttf
///
///
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

// class AllCatIcon {
//   AllCatIcon._();

//   static const _kFontFam = 'AllCatIcon';
//   static const String _kFontPkg = null;

//   static const IconData assignment_return =
//       IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData access_alarms =
//       IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
//   static const IconData menu_icon =
//       IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
// }

/// Flutter icons AllCatIcon
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AllCatIcon
///      fonts:
///       - asset: fonts/AllCatIcon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class AllCatIcon {
  AllCatIcon._();

  static const _kFontFam = 'AllCatIcon';
  static const String? _kFontPkg = null;

  static const IconData menu_icon =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

class TradeIicon {
  TradeIicon._();

  static const _kFontFam = 'TradeIicon';
  static const String? _kFontPkg = null;

  static const IconData app_icon_black_3d__1_ =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
